
services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: mp-next-auth
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
